language: java
jdk:
  - oraclejdk8

script: "mvn cobertura:cobertura"

before_install:
  - pip install --user codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  except:
    - appveyor