language: java
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -t d08d97e1-97ac-4941-90fe-259000192f3c
branches:
  except:
    - appveyor